title: Tommy Swimmer # name of the site
author: Tommy Swimmer # name of site's author
email: tommyswimmer@gmail.com # email of site's author
url: https://tommy-swimmer.github.io # root address of the site
baseurl: "/home" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: |\n # description of the site (multiple lines allowed)
··Water goes to the desert\n
··Collects in small pools\n
··Meditates\n
··\n

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: "Home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
